#!/bin/bash
#===============================================================================
#
#          FILE:  import.sh
# 
#         USAGE:  ./import.sh 
# 
#   DESCRIPTION:  import project from svn
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  amoblin 崔 (), amoblin@gmail.com
#       COMPANY:  bistu
#       VERSION:  1.0
#       CREATED:  2009年04月24日 16时10分20秒 CST
#      REVISION:  ---
#===============================================================================

PROJECT_NAME=gmystar
PROJECT_HOME=~/Projects/$PROJECT_NAME
cd $PROJECT_HOME
PROJECT_tmp=$PROJECT_NAME-`date +%Y-%m-%d`
PROJECT_tmp_uri=~/Dropbox/Public/$PROJECT_tmp
mkdir -p $PROJECT_tmp_uri

cp * $PROJECT_tmp_uri
cp -r src $PROJECT_tmp_uri
cp -r shot $PROJECT_tmp_uri
cp -r data $PROJECT_tmp_uri

cd ~/Dropbox/Public/
mkdir -p $PROJECT_tmp/bin $PROJECT_tmp/obj
mkdir -p $PROJECT_tmp/obj/tinyxml

find $PROJECT_temp -type d -name ".svn" -exec rm -rf {} \;
tar jcvf $PROJECT_tmp.tar.bz2 $PROJECT_tmp
rm -rf $PROJECT_tmp
